# This workflow will gather and install the latest version of Labeller using pip

name: PyPI install

on:
  push:
    branches: [ main ]

# Eventually, we will want to just test on 
# new releases rather than every push, e.g:
# on: release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    # - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Labeller
      run: |
        python -m pip install --upgrade pip
        pip install labeller
    - name: Test import of Labeller after install
      run: |
        # python -c "from labeller import *"
        mkdir images
        python -m labeller class1 class2 class3
